spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/repo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      client-type: lettuce
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

